wisersoft.ui/Models/Agricultores.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WiserSoft.UI.Models
{
    public class Agricultores
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "Cédula es requerido")]
        [MinLength(9, ErrorMessage = "Debe contener mínimo 9 caracteres")]
        public String Agr_Cedula { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Nombre es requerido")]
        [MinLength(2, ErrorMessage = "Debe contener mínimo 2 caracteres")]
        [MaxLength(100, ErrorMessage = "Debe contener máximo 100 caracteres")]
        public String Agr_Nombre { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Apellido es requerido")]
        [MinLength(2, ErrorMessage = "Debe contener mínimo 2 caracteres")]
        [MaxLength(100, ErrorMessage = "Debe contener máximo 100 caracteres")]
        public String Agr_Apellidos { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "El alias es requerido")]
        [MinLength(2, ErrorMessage = "Debe contener mínimo 2 caracteres")]
        [MaxLength(100, ErrorMessage = "Debe contener máximo 100 caracteres")]
        public String Agr_Alias { get; set; }

        public String Agr_Descripcion { get; set; }
        public int Agr_Distrito { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Teléfono es requerido")]
        [Phone(ErrorMessage = "Debe ingresar un número válido")]
        [MinLength(8, ErrorMessage = "Debe contener mínimo 8 caracteres")]
        public String Agr_Telefono { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Teléfono es requerido")]
        public int Agr_Feria_A_La_Que_Asiste { get; set; }

        public byte[] Agr_Foto { get; set; }

        public int Agr_Estado { get; set; }

        public Distritos Distritos { get; set; }
        public Cantones Cantones { get; set; }
        public Provincias Provincias { get; set; }

        public Ferias_Agricolas Ferias_Agricolas { get; set; }

        public List<Productos_Por_Agricultor> Productos { get; set; }
    }
}

wisersoft.ui/Controllers/AgricultoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WiserSoft.DAL.Interfaces;
using WiserSoft.DAL.Metodos;
using AutoMapper;


namespace WiserSoft.UI.Controllers
{
    public class AgricultoresController : Controller
    {
        IAgricultores agr;
        IDistritos dis;
        IProvincias pro;
        ICantones can;
        IFerias_Agricolas fer;


        public AgricultoresController()
        {
            agr = new MAgricultores();
            dis = new MDistritos();
            can = new MCantones();
            pro = new MProvincias();
            fer = new MFerias_Agricolas();
        }

        public ActionResult Index()
        {

            if (Session["UserID"] != null && Session["Type"].Equals("admin"))
            {
                if (TempData["delete"] != null)
                {
                    if (TempData["delete"].ToString() != "")
                    {

                        ModelState.AddModelError("error_delete", TempData["delete"].ToString());
                        TempData["delete"] = "";
                    }
                }

                    ViewBag.UserId = Session["UserID"];
               
                    List<DATA.Ferias_Agricolas> listaFerias = fer.ListarFerias_Agricolas();
                    List<DATA.Distritos> listaDistritos = dis.ListarDistritos();
                    List<DATA.Agricultores> listaAgricultores = agr.ListarAgricultores();

                    var agricultores = Mapper.Map<List<Models.Agricultores>>(listaAgricultores);
                    var ferias = Mapper.Map<List<Models.Ferias_Agricolas>>(listaFerias);
                    var distritos = Mapper.Map<List<Models.Distritos>>(listaDistritos);

                    foreach (Models.Agricultores agricultor in agricultores)
                    {
                        agricultor.Distritos = distritos.Where(x => x.dis_id == agricultor.Agr_Distrito).FirstOrDefault();
                        agricultor.Ferias_Agricolas = ferias.Where(x => x.Fa_Id == agricultor.Agr_Feria_A_La_Que_Asiste).FirstOrDefault();
                    }

                    return View(agricultores);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }

        public ActionResult Create()
        {
            if (Session["UserID"] != null && Session["Type"].Equals("admin"))
            {
                var listaFerias = fer.ListarFerias_Agricolas();
                var listaProvincia = pro.ListarProvincias();

                IEnumerable<SelectListItem> selectProvincias =
                from c in listaProvincia
                select new SelectListItem
                {
                    Text = c.Pro_nombre,
                    Value = c.Pro_id.ToString()
                };

                IEnumerable<SelectListItem> selectFerias =
                from c in listaFerias
                select new SelectListItem
                {
                    Text = c.Fa_Nombre,
                    Value = c.Fa_Id.ToString()
                };

                ViewBag.Provincia = selectProvincias;
                ViewBag.Ferias = selectFerias;

                ViewBag.Cantones = Enumerable.Empty<SelectListItem>();

                ViewBag.Distritos = Enumerable.Empty<SelectListItem>();

                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }


        [HttpPost]
        public ActionResult Create(Models.Agricultores agricultores)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var file = Request.Files["Photo"];

                    if (file != null)
                    {
                        byte[] fileBytes = new byte[file.ContentLength];
                        file.InputStream.Read(fileBytes, 0, file.ContentLength);
                        agricultores.Agr_Foto = fileBytes;
                        // ... now fileBytes[] is filled with the contents of the file.
                    }

                    string varSwitch = Request.Form["switch"].Split(',')[0];
                    if (varSwitch == "true")
                        agricultores.Agr_Estado = 1;
                    else
                        agricultores.Agr_Estado = 0;

                    var agrInsertar = Mapper.Map<DATA.Agricultores>(agricultores);
                    agr.InsertarAgricultor(agrInsertar);
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {

                    ModelState.AddModelError("error_agricultor", "No se pudo Agregar el agricultor.");
                }

            }
            else
            {
                try
                {
                    List<DATA.Distritos> listaDistritos = dis.ListarDistritos();
                    var distritos = Mapper.Map<List<Models.Distritos>>(listaDistritos);

                    List<DATA.Cantones> listaCantones = can.ListarCantones();
                    var cantones = Mapper.Map<List<Models.Cantones>>(listaCantones);

                    List<DATA.Provincias> listaProvincias = pro.ListarProvincias();
                    var provincias = Mapper.Map<List<Models.Provincias>>(listaProvincias);

                    List<DATA.Ferias_Agricolas> listaFerias = fer.ListarFerias_Agricolas();
                    var ferias = Mapper.Map<List<Models.Ferias_Agricolas>>(listaFerias);

                    var listaFeria = fer.ListarFerias_Agricolas();
                    var listaProvincia = pro.ListarProvincias();

                    IEnumerable<SelectListItem> selectProvincias =
                    from c in listaProvincia
                    select new SelectListItem
                    {
                        Text = c.Pro_nombre,
                        Value = c.Pro_id.ToString()
                    };

                    IEnumerable<SelectListItem> selectFerias =
                    from c in listaFerias
                    select new SelectListItem
                    {
                        Text = c.Fa_Nombre,
                        Value = c.Fa_Id.ToString()
                    };

                    ViewBag.Provincia = selectProvincias;
                    ViewBag.Ferias = selectFerias;

                    if (agricultores.Provincias.Pro_id == 0)
                    {
                        ViewBag.Cantones = Enumerable.Empty<SelectListItem>();
                    }
                    else
                    {

                        var listaCanton = can.ListarCantones();
                        IEnumerable<SelectListItem> selectCantones =
                        from c in listaCanton.Where(x => x.cnt_provincia == Convert.ToInt32(agricultores.Provincias.Pro_id))
                        select new SelectListItem
                        {
                            Text = c.cnt_nombre,
                            Value = c.cnt_id.ToString()
                        };

                        ViewBag.Cantones = selectCantones;
                    }

                    if (agricultores.Cantones.cnt_id != 0)
                    {
                        var listaDistrito = dis.ListarDistritos();
                        IEnumerable<SelectListItem> selectDistritos =
                        from c in listaDistrito.Where(x => x.dis_canton == Convert.ToInt32(agricultores.Cantones.cnt_id))
                        select new SelectListItem
                        {
                            Text = c.dis_nombre,
                            Value = c.dis_id.ToString()
                        };

                        ViewBag.Distritos = selectDistritos;
                    }
                    else
                    {
                        ViewBag.Distritos = Enumerable.Empty<SelectListItem>();
                    }
                }
                catch (Exception)
                {

                    ModelState.AddModelError("error_agricultor", "No se pudo Agregar el agricultor.");
                }



            }
            return View();
        }
        public ActionResult Edit(String id)
        {
            if (Session["UserID"] != null && Session["Type"].Equals("admin"))
            {
                    var agricultor = agr.BuscarAgricultor(id);
                    var agricultorBuscar = Mapper.Map<Models.Agricultores>(agricultor);

                    List<DATA.Distritos> listaDistritos = dis.ListarDistritos();
                    var distritos = Mapper.Map<List<Models.Distritos>>(listaDistritos);

                    List<DATA.Cantones> listaCantones = can.ListarCantones();
                    var cantones = Mapper.Map<List<Models.Cantones>>(listaCantones);

                    List<DATA.Provincias> listaProvincias = pro.ListarProvincias();
                    var provincias = Mapper.Map<List<Models.Provincias>>(listaProvincias);

                    List<DATA.Ferias_Agricolas> listaFerias = fer.ListarFerias_Agricolas();
                    var ferias = Mapper.Map<List<Models.Ferias_Agricolas>>(listaFerias);

                    agricultorBuscar.Ferias_Agricolas = ferias.Where(x => x.Fa_Id == agricultorBuscar.Agr_Feria_A_La_Que_Asiste).FirstOrDefault();
                    agricultorBuscar.Distritos = distritos.Where(x => x.dis_id == agricultorBuscar.Agr_Distrito).FirstOrDefault();
                    agricultorBuscar.Cantones = cantones.Where(x => x.cnt_id == agricultorBuscar.Distritos.dis_canton).FirstOrDefault();
                    agricultorBuscar.Provincias = provincias.Where(x => x.Pro_id == agricultorBuscar.Cantones.cnt_provincia).FirstOrDefault();
                    ViewData["idCanton"] = agricultorBuscar.Cantones.cnt_id;

                    var listaProvincia = pro.ListarProvincias();
                    var listaFeria = fer.ListarFerias_Agricolas();

wisersoft.ui/Views/Agricultores/Create.cshtml
@model WiserSoft.UI.Models.Agricultores

@{
    ViewBag.Title = "Crear";

}


@using (Html.BeginForm("Create",
                                                            "Agricultores",
                                                            FormMethod.Post,
                                                            new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">
                        Creación
                    </h1>
                    <ol class="breadcrumb">
                        <li>
                            <i class="fa fa-fw fa-child"></i> @Html.ActionLink("Agricultores", "Index", "Agricultores")
                        </li>
                        <li class="active">
                            <i class="fa fa-edit"></i> Crear agricultor
                        </li>
                    </ol>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <form role="form">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <br />
                        <div class="form-group input-group col-md-10">
                            @Html.Label("Cedula", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Agr_Cedula, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Agr_Cedula, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="form-group form-group input-group col-md-10">
                            @Html.Label("Nombre", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Agr_Nombre, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Agr_Nombre, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="form-group input-group col-md-10">
                            @Html.Label("Apellidos", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Agr_Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Agr_Apellidos, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="form-group input-group col-md-10">
                            @Html.Label("Alias", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Agr_Alias, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Agr_Alias, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="form-group input-group col-md-10">
                            @Html.Label("Descripcion", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Agr_Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Agr_Descripcion, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group input-group col-md-10">
                            @Html.Label("Provincia", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("Provincia",
                               new SelectList(ViewBag.Provincia, "Value", "Text"),
                               "Seleccione una provincia:",
                               new { @class = "form-control", @onchange = "BuscarCantones()" })
                            </div>
                        </div>
                        <br />
                        <div class="form-group input-group col-md-10">
                            @Html.Label("Canton", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("Canton",
                               new SelectList(ViewBag.Cantones, "Value", "Text"),
                               "Seleccione un canton",
                               new { @class = "form-control", @onchange = "BuscarDistritos()" })
                            </div>
                        </div>
                        <br />
                        <div class="form-group input-group col-md-10">
                            @Html.Label("Distrito", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.Agr_Distrito,
                               new SelectList(ViewBag.Distritos, "Value", "Text"),
                               "Seleccione un distrito",
                               new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Agr_Distrito, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="form-group input-group col-md-10">
                            @Html.Label("Telefono", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Agr_Telefono, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Agr_Telefono, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="form-group input-group col-md-10">
                            @Html.Label("Feria a la que asiste", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.Agr_Feria_A_La_Que_Asiste,
                                new SelectList(ViewBag.Ferias, "Value", "Text"),
                                "Seleccione una feria:",
                                new { @class = "form-control", @onchange = "" })
                                @Html.ValidationMessageFor(model => model.Agr_Feria_A_La_Que_Asiste, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="form-group input-group col-md-10">
                            @Html.Label("Foto", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                <input type="file" name="Photo" id="Photo" />
                            </div>
                        </div>
                        <br />
                        <div class="form-group input-group col-md-10">
                            @Html.Label("Activo", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.CheckBox("switch",true)
                            </div>
                        </div>
                        <br />
                        <div class="form-group">
                            <div class="col-md-offset-1 col-md-10">
                                <button class="btn btn-custom" onclick="location.href='@Url.Action("Index", "Agricultores")';return false;"><i class="fa fa-arrow-left"></i> Volver</button>
                                <input type="submit" value="Crear dato" class="btn btn-custom" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    
    <script src="~/Scripts/Ferias_Agricolas/jquery-1.7.1.min.js"></script>
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>


    <script>


        function BuscarCantones() {
            var Pro_id = $('#Provincia').val();
            $.ajax(
                {
                    url: '/Agricultores/BuscarCantones',
                    type: "GET",
                    dataType: "JSON",
                    data: { idProvincia: Pro_id },
                    success: function (selectCantones) {
                        $("#Canton").html(""); // clear before appending new list
                        $("#Canton").append($('<option></option>').val("").html("Seleccione un canton:"));
                        $.each(selectCantones, function (i, canton) {
                            $("#Canton").append($('<option></option>').val(canton.Value).html(canton.Text));
                        });
                    },
                    error: function (xhr, status, error) {
                        alert(xhr.responseText);
                    }
                });
        }

        function BuscarDistritos() {
            var Cant_id = $('#Canton').val();
            $.ajax(
                {
                    url: '/Agricultores/BuscarDistritos',
                    type: "GET",
                    dataType: "JSON",
                    data: { idCanton: Cant_id },
                    success: function (selectDistritos) {
                        $("#Agr_Distrito").html(""); // clear before appending new list
                        $("#Agr_Distrito").append($('<option></option>').val("").html("Seleccione un distrito:"));
                        $.each(selectDistritos, function (i, distrito) {
                            $("#Agr_Distrito").append($('<option></option>').val(distrito.Value).html(distrito.Text));
                        });
                    },
                    error: function (xhr, status, error) {
                        alert(xhr.responseText);
                    }
                });

        }
    </script>
}

wisersoft.ui/Views/Agricultores/Delete.cshtml
@model WiserSoft.UI.Models.Agricultores

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Agricultores</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Agr_Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agr_Cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Agr_Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agr_Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Agr_Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agr_Apellidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Agr_Alias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agr_Alias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Agr_Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agr_Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Agr_Distrito)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agr_Distrito)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Agr_Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agr_Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Agr_Feria_A_La_Que_Asiste)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agr_Feria_A_La_Que_Asiste)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Agr_Foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agr_Foto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Agr_Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agr_Estado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Volver a la Lista", "Index")
        </div>
    }
</div>

wisersoft.ui/Views/Agricultores/Index.cshtml
@model IEnumerable<WiserSoft.UI.Models.Agricultores>

@{
    ViewBag.Title = "Agricultores";
}

<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Agricultores
                </h1>
                <ol class="breadcrumb">
                    <li>
                        <i class="fa fa-child"></i> @Html.ActionLink("Agricultores", "Index", "Agricultores")
                    </li>
                    <li class="active">
                        <i class="fa fa-tag"></i> Productos
                    </li>
                </ol>
            </div>
        </div>
        

        <div class="row">
            <div class="col-lg-12">
                <div class="table-responsive">
                    <div style="text-align:center">
                        @Html.ValidationMessage("error_delete", new { @class = "text-danger" })
                    </div>
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayName("Cédula")
                                </th>
                                <th>
                                    @Html.DisplayName("Nombre")
                                </th>
                                <th>
                                    @Html.DisplayName("Apellidos")
                                </th>
                                <th>
                                    @Html.DisplayName("Alias")
                                </th>
                                <th>
                                    @Html.DisplayName("Descripción")
                                </th>
                                <th>
                                    @Html.DisplayName("Distrito")
                                </th>
                                <th>
                                    @Html.DisplayName("Teléfono")
                                </th>
                                <th>
                                    @Html.DisplayName("Feria que asiste")
                                </th>
                                <th>
                                    @Html.DisplayName("Foto")
                                </th>
                               
                                <th>@Html.ActionLink("Crear agricultor", "Create")</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Agr_Cedula)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Agr_Nombre)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Agr_Apellidos)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Agr_Alias)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Agr_Descripcion)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Distritos.dis_nombre)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Agr_Telefono)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Ferias_Agricolas.Fa_Nombre)
                                    </td>
                                    <td>
                                        @{
                                            var base64 = Convert.ToBase64String(item.Agr_Foto);
                                            var imgSrc = String.Format("data:image/gif; base64, {0}", base64);
                                        }
                                        <img src="@imgSrc" class="img-responsive img-rounded" width="200" height="200" />

                                    </td>
                                   
                                    <td>
                                        @Html.ActionLink("Editar", "Edit", new { id = item.Agr_Cedula }, new { @class = "btn btn-custom" })  |
                                        @Html.ActionLink("Eliminar", "Delete", new { id = item.Agr_Cedula }, new { @class = "btn btn-custom" })
                                    </td>
                                </tr>
                                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>