wisersoft.ui/Controllers/ComprasController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WiserSoft.DAL.Interfaces;
using WiserSoft.DAL.Metodos;

namespace WiserSoft.UI.Controllers
{
    public class ComprasController : Controller
    {
        IProvincias prov;
        ICantones can;
        IDistritos dis;
        IProductos pro;
        IClasificacion cla;
        IMedidas med;
        IAgricultores agr;
        IProductos_Por_Agricultor ppa;
        ICanastas canas;
        ICompras com;
        // GET: Ferias_Agricolas

        public ComprasController()
        {
            prov = new MProvincias();
            can = new MCantones();
            dis = new MDistritos();
            pro = new MProductos();
            cla = new MClasificacion();
            med = new MMedidas();
            agr = new MAgricultores();
            ppa = new MProductos_Por_Agricultor();
            canas = new MCanastas();
            com = new MCompras();
        }

        

        public ActionResult Index()
        {
            if (Session["UserID"] != null && Session["Type"].Equals("cliente"))
            {
                if (Session["Feria"] != null)
                {
                    //Session["Feria"]  = 1;
                    //Session["Cliente"] = "pgomez";

                    if (TempData["Agricultores"] != null)
                    {
                        ViewData["Agricultores"] = TempData["Agricultores"];
                        ViewData["Clasificacion"] = TempData["Clasificacion"];
                        ViewData["filProducto"] = TempData["filProducto"];
                        ViewData["canasta"] = TempData["canasta"];
                    }
                    else
                    {
                        List<DATA.Distritos> listaDistritos = dis.ListarDistritos();
                        var distritos = Mapper.Map<List<Models.Distritos>>(listaDistritos);

                        List<DATA.Cantones> listaCantones = can.ListarCantones();
                        var cantones = Mapper.Map<List<Models.Cantones>>(listaCantones);

                        List<DATA.Provincias> listaProvincias = prov.ListarProvincias();
                        var provincias = Mapper.Map<List<Models.Provincias>>(listaProvincias);

                        List<DATA.Agricultores> listaAgricultores = agr.ListarAgricultores();
                        var agricultores = Mapper.Map<List<Models.Agricultores>>(listaAgricultores);

                        List<DATA.Productos_Por_Agricultor> listaProductosPorProductor = ppa.ListarProductos_Por_Agricultor();
                        var productosPorAgricultor = Mapper.Map<List<Models.Productos_Por_Agricultor>>(listaProductosPorProductor);

                        List<DATA.Productos> listaProductos = pro.ListarProductos();
                        var productos = Mapper.Map<List<Models.Productos>>(listaProductos);

                        List<DATA.Clasificacion> listaClasificacion = cla.ListarClasificaciones();
                        var clasificacion = Mapper.Map<List<Models.Clasificacion>>(listaClasificacion);

                        List<DATA.Canastas> listaCanastas = canas.ListarCanastas();
                        var canastas = Mapper.Map<List<Models.Canastas>>(listaCanastas).Where(x => x.Can_feria == Convert.ToInt32(Session["feria"])).Where(x => x.Can_usuario == Session["UserID"].ToString()).OrderByDescending(x => x.Can_id).ToList();

                        List<DATA.Medidas> listaMedidas = med.ListarMedidas();
                        var medidas = Mapper.Map<List<Models.Medidas>>(listaMedidas);

                        foreach (Models.Productos producto in productos)
                        {
                            producto.Clasificacion = clasificacion.Where(x => x.Clasi_Id == producto.Pdt_tipo).FirstOrDefault();
                            producto.Medidas = medidas.Where(x => x.Mdd_Id == producto.Pdt_unidad_de_medida).FirstOrDefault();
                        }

                        foreach (Models.Productos_Por_Agricultor ppa in productosPorAgricultor)
                        {
                            ppa.Producto = productos.Where(x => x.Pdt_id == ppa.Ppa_Id_Producto).FirstOrDefault();
                        }

                        foreach (Models.Agricultores agricultor in agricultores)
                        {
                            agricultor.Distritos = distritos.Where(x => x.dis_id == agricultor.Agr_Distrito).FirstOrDefault();
                            agricultor.Cantones = cantones.Where(x => x.cnt_id == agricultor.Distritos.dis_canton).FirstOrDefault();
                            agricultor.Provincias = provincias.Where(x => x.Pro_id == agricultor.Cantones.cnt_provincia).FirstOrDefault();
                            agricultor.Productos = productosPorAgricultor.Where(x => x.Ppa_Id_Agricultor == agricultor.Agr_Cedula).ToList();
                        }
                        agricultores = agricultores.Where(x => x.Productos.Count > 0).ToList();
                        ViewData["Agricultores"] = agricultores;

                        foreach (var item in clasificacion)
                        {
                            item.usadoEnFiltro = 1;
                        }

                        ViewData["Clasificacion"] = clasificacion;
                        ViewData["filProducto"] = "";

                        foreach (var item in canastas)
                        {
                            item.seleccionada = 0;
                        }

                        ViewData["canasta"] = canastas;
                    }
                    return View();
                }
                else {
                    return RedirectToAction("Index", "SeleccionDeFeria");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult Buscar(String filProducto, String filtro, string txtcesta, string cmbcesta)
        {
            List<DATA.Distritos> listaDistritos = dis.ListarDistritos();
            var distritos = Mapper.Map<List<Models.Distritos>>(listaDistritos);

            List<DATA.Cantones> listaCantones = can.ListarCantones();
            var cantones = Mapper.Map<List<Models.Cantones>>(listaCantones);

            List<DATA.Provincias> listaProvincias = prov.ListarProvincias();
            var provincias = Mapper.Map<List<Models.Provincias>>(listaProvincias);

            List<DATA.Agricultores> listaAgricultores = agr.ListarAgricultores();
            var agricultores = Mapper.Map<List<Models.Agricultores>>(listaAgricultores);

            List<DATA.Productos_Por_Agricultor> listaProductosPorProductor = ppa.ListarProductos_Por_Agricultor();
            var productosPorAgricultor = Mapper.Map<List<Models.Productos_Por_Agricultor>>(listaProductosPorProductor);

            List<DATA.Productos> listaProductos = pro.ListarProductos();
            var productos = Mapper.Map<List<Models.Productos>>(listaProductos);

            List<DATA.Clasificacion> listaClasificacion = cla.ListarClasificaciones();
            var clasificacion = Mapper.Map<List<Models.Clasificacion>>(listaClasificacion);

            List<DATA.Canastas> listaCanastas = canas.ListarCanastas();
            var canastas = Mapper.Map<List<Models.Canastas>>(listaCanastas).Where(x => x.Can_feria == Convert.ToInt32(Session["feria"])).OrderByDescending(x => x.Can_id).ToList();

            List<DATA.Medidas> listaMedidas = med.ListarMedidas();
            var medidas = Mapper.Map<List<Models.Medidas>>(listaMedidas);
            productos = productos.Where(x => x.Pdt_nombre.Contains(filProducto)).ToList();

            foreach (Models.Productos producto in productos)
            {
                producto.Clasificacion = clasificacion.Where(x => x.Clasi_Id == producto.Pdt_tipo).FirstOrDefault();
                producto.Medidas = medidas.Where(x => x.Mdd_Id == producto.Pdt_unidad_de_medida).FirstOrDefault();
            }
            
            productos = productos.Where(x => filtro.Contains(x.Clasificacion.Clasi_Nombre)).ToList();
            //productos = productos.Where(x =>  filtro.IndexOf(x.Clasificacion.Clasi_Nombre) >= 0).ToList();
            //productos = productos.Where(x =>"banano".IndexOf(x.Pdt_nombre) >=0 ).ToList();

            foreach (Models.Productos_Por_Agricultor ppa in productosPorAgricultor)
            {
                ppa.Producto = productos.Where(x => x.Pdt_id == ppa.Ppa_Id_Producto).FirstOrDefault();
            }
            productosPorAgricultor = productosPorAgricultor.Where(x => x.Producto != null).ToList();

            foreach (Models.Agricultores agricultor in agricultores)
            {
                agricultor.Distritos = distritos.Where(x => x.dis_id == agricultor.Agr_Distrito).FirstOrDefault();
                agricultor.Cantones = cantones.Where(x => x.cnt_id == agricultor.Distritos.dis_canton).FirstOrDefault();
                agricultor.Provincias = provincias.Where(x => x.Pro_id == agricultor.Cantones.cnt_provincia).FirstOrDefault();
                agricultor.Productos = productosPorAgricultor.Where(x => x.Ppa_Id_Agricultor == agricultor.Agr_Cedula).ToList();
            }

            agricultores = agricultores.Where(x => x.Productos.Count > 0).ToList();

            TempData["Agricultores"] = agricultores;

            foreach (var item in clasificacion)
            {
                if (filtro.IndexOf(item.Clasi_Nombre) >= 0)
                {
                    item.usadoEnFiltro = 1;
                }
                else
                {
                    item.usadoEnFiltro = 0;
                }
                
            }

            TempData["Clasificacion"] = clasificacion;
            TempData["filProducto"] = filProducto;

            if (txtcesta!="")
            {
                DateTime hoy = DateTime.Today;

wisersoft.ui/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WiserSoft.DAL.Interfaces;
using WiserSoft.DAL.Metodos;
using AutoMapper;



namespace WiserSoft.UI.Controllers
{
    public class UsersController : Controller
    {
        IUsers use;

        public UsersController()
        {
            use = new MUsers();
        }

        //
        // GET: /Users/

        public ActionResult Index()
        {
            if (Session["UserID"] != null && Session["Type"].Equals("admin"))
            {
                var listaUsers = use.ListarUsers();

                var users = Mapper.Map<List<Models.Users>>(listaUsers);
                return View(users);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
           
        }

        public ActionResult Create()
        {
            if (Session["UserID"] != null && Session["Type"].Equals("admin"))
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult Create(Models.Users users)
        {

            if (Session["UserID"] != null && Session["Type"].Equals("admin"))
            {
                try
                {
                    if (ModelState.IsValid)
                    { 
                        //Encripta el password
                        var passwordEncriptado = Encriptacion.Encriptacion.Encriptar(users.Us_Password);
                        //Asigna la variable encriptada al objeto Password
                        users.Us_Password = passwordEncriptado;

                        var usersInsertar = Mapper.Map<DATA.Users>(users);
                        use.InsertarUsers(usersInsertar);
                        return RedirectToAction("Index");
                    }
                   
                }
                catch (Exception)
                {
                    ModelState.AddModelError("error", "No se ha podido insertar");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            return View();


        }

        public ActionResult Edit(string us_User_Name)
        {
            if (Session["UserID"] != null && Session["Type"].Equals("admin"))
            {
                var users = use.BuscarUsers(us_User_Name);
                var usersBuscar = Mapper.Map<Models.Users>(users);
                //Decripta el password
                var passwordDecriptado = Encriptacion.Encriptacion.Decriptar(usersBuscar.Us_Password);
                //Asigna la variable decriptada al objeto Password
                usersBuscar.Us_Password = passwordDecriptado;
                usersBuscar.ConfirmPassowrd = passwordDecriptado;

                return View(usersBuscar);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            
        }

        [HttpPost]
        public ActionResult Edit(Models.Users users)
        {
            if (Session["UserID"] != null && Session["Type"].Equals("admin"))
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        //Encripta el password
                        var passwordEncriptado = Encriptacion.Encriptacion.Encriptar(users.Us_Password);
                        //Asigna la variable encriptada al objeto Password
                        users.Us_Password = passwordEncriptado;

                        var usersEditar = Mapper.Map<DATA.Users>(users);
                        use.ActualizarUsers(usersEditar);
                        return RedirectToAction("Index");
                    }
                    catch (Exception)
                    {
                        ModelState.AddModelError("error", "No se ha podido actualizar");
                    }
                   
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        public ActionResult Delete(string us_User_Name)
        {
            use.EliminarUsers(us_User_Name);
            return RedirectToAction("Index");
        }

    }
}

wisersoft.ui/Views/Shared/_Layout_Administrador.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="~/Scripts/Chart.min.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

    <title>@ViewBag.Title - FAV</title>
    @Styles.Render("~/Content/Admin")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="@Url.Action("UserDashboard", "Home")" class="navbar-brand">Administración FAV</a>
        </div>
        <ul class="nav navbar-right top-nav">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> @Session["UserID"].ToString().ToUpper()<b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li class="divider"></li>
                    <li>
                        @Html.Partial("_LoginParcial")
                    </li>
                </ul>
            </li>
        </ul>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav side-nav">
                <li>
                    <a href="@Url.Action("Index", "Agricultores")"><i class="fa fa-fw fa-child"></i> Agricultores</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Clasificacion")"><i class="fa fa-fw fa-list"></i> Clasificaciones</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Clientes")"><i class="fa fa-fw fa-child"></i> Clientes</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Ferias_Agricolas")"><i class="fa fa-fw fa-map-marker"></i> Ferias Agricolas</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Medidas")"><i class="fa fa-fw fa-sort-numeric-asc"></i> Medidas</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Productos")"><i class="fa fa-fw fa-shopping-cart"></i> Productos</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Productos_Por_Agricultor")"><i class="fa fa-fw fa-lemon-o"></i> Productos por Agricultor</a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Users")"><i class="fa fa-fw fa-users"></i> Usuarios</a>
                </li>
            </ul>
        </div>
    </nav>

    <div id="wrapper">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/Admin")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

wisersoft.ui/Views/Shared/_Layout_Cliente.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FAV</title>
    @Styles.Render("~/Content/Cliente")

</head>
<body>
    <header class="navbar navbar-sticky">

        <div class="site-branding">
            <div class="inner">
                <a href="@Url.Action("Index", "SeleccionDeFeria")" class="site-logo"><img src="~/images/logo.png" alt="Logo"></a>
            </div>
        </div>

        <nav class="site-menu">
            <ul>
                <li class="active">
                    <a href="@Url.Action("Index", "SeleccionDeFeria")"><span>Selección de feria</span></a>
                </li>
                <li class="active">
                    <a href="@Url.Action("Index", "Compras")"><span>Comprar</span></a>

                </li>

                <li class="active">
                    <a href="@Url.Action("Pago", "Compras")"><span>Pagar</span></a>

                </li>

            </ul>
        </nav>
        <!-- Toolbar-->
        <div class="toolbar">
            <div class="inner">
                <div class="tools">
                    <div class="account">
                       <i class="icon-head"></i>
                        <ul class="toolbar-dropdown">
                            <li class="sub-menu-title"><span>Bienvenido,</span> @Session["Nombre"].ToString().ToUpper()</li>
                            <li><a href="@Url.Action("Edit","Clientes", new { cedula = Session["Cedula"].ToString() } )">Mi perfil</a></li>
                            <li class="sub-menu-separator"></li>
                            <li>
                                @Html.Partial("_LoginParcialCliente")
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - FAV by WiserSoft</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")

    @RenderSection("scripts", required: false)
</body>
</html>

wisersoft.ui/Views/Shared/_LoginParcial.cshtml
@using (Html.BeginForm("Logout", "Home", FormMethod.Post, new { id = "logoutForm"}))
{
    <a href="javascript:document.getElementById('logoutForm').submit()" style="margin-left:20px;"><i class="fa fa-fw fa-power-off"></i> Cerrar sesión</a>
}

wisersoft.ui/Views/Shared/_LoginParcialCliente.cshtml
@using (Html.BeginForm("Logout", "Home", FormMethod.Post, new { id = "logoutForm"}))
{
    <a href="javascript:document.getElementById('logoutForm').submit()" style="margin-left:20px;"><i class="icon-unlock"></i> Cerrar sesión</a>
}