wisersoft.ui/Models/Clasificacion.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WiserSoft.UI.Models
{
    public class Clasificacion
    {
        public int Clasi_Id { get; set; }

        [Required(ErrorMessage = "Nombre clasificación es requerido")]
        [MinLength(2, ErrorMessage = "El número mínimo de caracteres es de 2")]
        [MaxLength(100, ErrorMessage = "El número máximo de caracteres es de 100")]
        public String Clasi_Nombre { get; set; }

        public int usadoEnFiltro { get; set; }
    }
}

wisersoft.ui/Controllers/ClasificacionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WiserSoft.DAL.Interfaces;
using WiserSoft.DAL.Metodos;
using AutoMapper;


namespace WiserSoft.UI.Controllers
{
    public class ClasificacionController : Controller
    {
        IClasificacion clasi;

        public ClasificacionController()
        {
            clasi = new MClasificacion();
        }

        // GET: /Clasificacion/
        public ActionResult Index()
        {
            if (Session["UserID"] != null && Session["Type"].Equals("admin"))
            {
                if (TempData["delete"] != null)
                {
                    if (TempData["delete"].ToString() != "")
                    {

                        ModelState.AddModelError("error_delete", TempData["delete"].ToString());
                        TempData["delete"] = "";
                    }
                }
                var listaClasificacion = clasi.ListarClasificaciones();
                var clasificaciones = Mapper.Map<List<Models.Clasificacion>>(listaClasificacion);
                return View(clasificaciones);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult Create()
        {
            if (Session["UserID"] != null && Session["Type"].Equals("admin"))
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            
        }

        [HttpPost]
        public ActionResult Create(Models.Clasificacion clasificacion)
        {
            if (Session["UserID"] != null && Session["Type"].Equals("admin"))
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        var clasificacionInsertar = Mapper.Map<DATA.Clasificacion>(clasificacion);
                        clasi.InsertarClasificacion(clasificacionInsertar);
                        return RedirectToAction("Index");
                    }
                    
                }
                catch (Exception)
                {

                    ModelState.AddModelError("error", "No se ha podido insertar una clasificación");
                }

            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        public ActionResult Edit(int clasi_id)
        {
            if (Session["UserID"] != null && Session["Type"].Equals("admin"))
            {
                try
                {
                    var clasificacion = clasi.BuscarClasificacion(clasi_id);
                    var clasificacionBuscar = Mapper.Map<Models.Clasificacion>(clasificacion);
                    return View(clasificacionBuscar);
                }
                catch (Exception)
                {

                    ModelState.AddModelError("error", "No se ha podido encontrar la clasificación");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(Models.Clasificacion clasificacion)
        {
            if (Session["UserID"] != null && Session["Type"].Equals("admin"))
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        var clasificacionEditar = Mapper.Map<DATA.Clasificacion>(clasificacion);
                        clasi.ActualizarClasificacion(clasificacionEditar);
                        return RedirectToAction("Index");
                    }
                   
                }
                catch (Exception)
                {

                    ModelState.AddModelError("error", "No se ha podido actualizar la clasificación");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int clasi_id)
        {
            if (Session["UserID"] != null && Session["Type"].Equals("admin"))
            {
                try
                {
                    clasi.EliminarClasificacion(clasi_id);
                }
                catch (Exception e)
                {
                    TempData["delete"] = "No se puede eliminar la clasificacion porque tiene información relacionada a ella.";
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
           
            return RedirectToAction("Index");
        }


    }
}

wisersoft.ui/Views/Clasificacion/Create.cshtml
@model WiserSoft.UI.Models.Clasificacion

@{
    ViewBag.Title = "Crear";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">
                        Creación
                    </h1>
                    <ol class="breadcrumb">
                        <li>
                            <i class="fa fa-th-list"></i> @Html.ActionLink("Clasificación", "Index", "Clasificacion")
                        </li>
                        <li class="active">
                            <i class="fa fa-edit"></i> Crear clasificación
                        </li>
                    </ol>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <form role="form">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        
                        <div class="form-group input-group col-md-8">
                            @Html.Label("Nombre:", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class=" col-md-10">
                                @Html.EditorFor(model => model.Clasi_Nombre, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Clasi_Nombre, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <br />
                        <div class="form-group">
                            <div class="col-md-offset-1 col-md-10">
                                <button class="btn btn-custom" onclick="location.href='@Url.Action("Index", "Clasificacion")';return false;"><i class="fa fa-arrow-left"></i> Volver</button>
                                <input type="submit" value="Crear dato" class="btn btn-custom" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}
<div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

wisersoft.ui/Views/Clasificacion/Delete.cshtml
@model WiserSoft.UI.Models.Clasificacion

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar clasificación</h2>

<h3>¿Está seguro que quiere borrar esto?</h3>
<div>
    <h4>Clasificacion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Clasi_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Clasi_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Clasi_Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Clasi_Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Volver a la lista", "Index")
        </div>
    }
</div>

wisersoft.ui/Views/Clasificacion/Edit.cshtml
@model WiserSoft.UI.Models.Clasificacion

@{
    ViewBag.Title = "Editar";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">
                        Edición
                    </h1>
                    <ol class="breadcrumb">
                        <li>
                            <i class="fa fa-th-list"></i> @Html.ActionLink("Clasificación", "Index", "Clasificacion")
                        </li>
                        <li class="active">
                            <i class="fa fa-edit"></i> Editar clasificación
                        </li>
                    </ol>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <form role="form">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group" style="display:none">
                            @Html.LabelFor(model => model.Clasi_Id, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Clasi_Id, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Clasi_Id, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <br />
                        <div class="form-group input-group col-md-8">
                            @Html.Label("Nombre:", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class=" col-md-10">
                                @Html.EditorFor(model => model.Clasi_Nombre, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Clasi_Nombre, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <br />
                        <div class="form-group">
                            <div class="col-md-offset-1 col-md-10">
                                <button class="btn btn-custom" onclick="location.href='@Url.Action("Index", "Clasificacion")';return false;"><i class="fa fa-arrow-left"></i> Volver</button>
                                <input type="submit" value="Editar datos" class="btn btn-custom" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}
<div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

wisersoft.ui/Views/Clasificacion/Index.cshtml
@model IEnumerable<WiserSoft.UI.Models.Clasificacion>

@{
    ViewBag.Title = "Clasificación";
}


<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    Clasificaciones
                </h1>
                <ol class="breadcrumb">
                    <li>
                        <i class="fa fa-th-list"></i> @Html.ActionLink("Clasificación", "Index", "Clasificacion")
                    </li>
                    <li class="active">
                        <i class="fa fa-tag"></i> Productos
                    </li>
                </ol>
            </div>
            <div style="text-align:center">
                @Html.ValidationMessage("error_delete", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                            <tr>
                                <th>@Html.DisplayName("Tipo")</th>
                                <th>@Html.ActionLink("Crear nueva clasificación", "Create")</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Clasi_Nombre)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Editar", "Edit", new { Clasi_Id = item.Clasi_Id }, new { @class = "btn btn-custom" })  |
                                        @Html.ActionLink("Eliminar", "Delete", new { Clasi_Id = item.Clasi_Id }, new { @class = "btn btn-custom" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>